The 3d homework

In [1]:
import wget

data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'
!wget -O car_price.csv $data

--2023-09-30 18:11:37--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: 'car_price.csv'

     0K .......... .......... .......... .......... ..........  3%  752K 2s
    50K .......... .......... .......... .......... ..........  6% 2.62M 1s
   100K .......... .......... .......... .......... .......... 10% 1.10M 1s
   150K .......... .......... .......... .......... .......... 13% 7.31M 1s
   200K .......... .......... .......... .......... .......... 17% 1.38M 1s
   250K .......... .......... .......... .......... .......... 20% 3.60M 1s
   300K .......... .......... .......... .......... .......... 24% 3.43M 1s
   350K .......... .......... .......... .......... .......... 27% 1.42M 1s
   400K .......... .......... .......... .......... .......... 31% 2.19M 1s
   450K .......... .......... .......... .......... .......... 34% 43.3M 0s
   500K .......... .......... .......... .......... .......... 38% 17.3M 0s
   550K .......... .......... .......... .......... .......... 41% 38.0M 0s
   600K .......... .......... .......... .......... .......... 45% 1.99M 0s
   650K .......... .......... .......... .......... .......... 48% 9.83M 0s
   700K .......... .......... .......... .......... .......... 52% 9.48M 0s
   750K .......... .......... .......... .......... .......... 55% 3.53M 0s
   800K .......... .......... .......... .......... .......... 58% 11.1M 0s
   850K .......... .......... .......... .......... .......... 62% 10.2M 0s
   900K .......... .......... .......... .......... .......... 65% 9.69M 0s
   950K .......... .......... .......... .......... .......... 69% 16.3M 0s
  1000K .......... .......... .......... .......... .......... 72% 12.9M 0s
  1050K .......... .......... .......... .......... .......... 76% 8.63M 0s
  1100K .......... .......... .......... .......... .......... 79% 8.31M 0s
  1150K .......... .......... .......... .......... .......... 83% 13.5M 0s
  1200K .......... .......... .......... .......... .......... 86% 16.9M 0s
  1250K .......... .......... .......... .......... .......... 90% 8.23M 0s
  1300K .......... .......... .......... .......... .......... 93% 26.4M 0s
  1350K .......... .......... .......... .......... .......... 97% 8.34M 0s
  1400K .......... .......... .......... ..........           100% 22.6M=0.4s

2023-09-30 18:11:38 (3.87 MB/s) - 'car_price.csv' saved [1475504/1475504]

In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv('car_price.csv')
df.T

,0,1,2,3,4,5,6,7,8,9,...,11904,11905,11906,11907,11908,11909,11910,11911,11912,11913
Make,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,...,BMW,BMW,Acura,Acura,Acura,Acura,Acura,Acura,Acura,Lincoln
Model,1 Series M,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,...,Z8,Z8,ZDX,ZDX,ZDX,ZDX,ZDX,ZDX,ZDX,Zephyr
Year,2011,2011,2011,2011,2011,2012,2012,2012,2012,2013,...,2002,2003,2011,2011,2011,2012,2012,2012,2013,2006
Engine Fuel Type,premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),...,premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (recommended),regular unleaded
Engine HP,335.0,300.0,300.0,230.0,230.0,230.0,300.0,300.0,230.0,230.0,...,394.0,394.0,300.0,300.0,300.0,300.0,300.0,300.0,300.0,221.0
Engine Cylinders,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,8.0,8.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
Transmission Type,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,...,MANUAL,MANUAL,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC
Driven_Wheels,rear wheel drive,rear wheel drive,rear wheel drive,rear wheel drive,rear wheel drive,rear wheel drive,rear wheel drive,rear wheel drive,rear wheel drive,rear wheel drive,...,rear wheel drive,rear wheel drive,all wheel drive,all wheel drive,all wheel drive,all wheel drive,all wheel drive,all wheel drive,all wheel drive,front wheel drive
Number of Doors,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
Market Category,"Factory Tuner,Luxury,High-Performance","Luxury,Performance","Luxury,High-Performance","Luxury,Performance",Luxury,"Luxury,Performance","Luxury,Performance","Luxury,High-Performance",Luxury,Luxury,...,"Exotic,Luxury,High-Performance","Exotic,Luxury,High-Performance","Crossover,Hatchback,Luxury","Crossover,Hatchback,Luxury","Crossover,Hatchback,Luxury","Crossover,Hatchback,Luxury","Crossover,Hatchback,Luxury","Crossover,Hatchback,Luxury","Crossover,Hatchback,Luxury",Luxury
Vehicle Size,Compact,Compact,Compact,Compact,Compact,Compact,Compact,Compact,Compact,Compact,...,Compact,Compact,Midsize,Midsize,Midsize,Midsize,Midsize,Midsize,Midsize,Midsize
Vehicle Style,Coupe,Convertible,Coupe,Coupe,Convertible,Coupe,Convertible,Coupe,Convertible,Convertible,...,Convertible,Convertible,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,Sedan
highway MPG,26,28,28,28,28,28,26,28,28,27,...,19,19,23,23,23,23,23,23,23,26
city mpg,19,19,20,18,18,18,17,20,18,18,...,12,12,16,16,16,16,16,16,16,17
Popularity,3916,3916,3916,3916,3916,3916,3916,3916,3916,3916,...,3916,3916,204,204,204,204,204,204,204,61
MSRP,46135,40650,36350,29450,34500,31200,44100,39300,36900,37200,...,130000,131500,46020,56570,50520,46120,56670,50620,50920,28995

In [7]:
df_short = df[['Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders', 'Transmission Type', 'Vehicle Style', 'highway MPG', 'city mpg']]
df_short.T

,0,1,2,3,4,5,6,7,8,9,...,11904,11905,11906,11907,11908,11909,11910,11911,11912,11913
Make,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,...,BMW,BMW,Acura,Acura,Acura,Acura,Acura,Acura,Acura,Lincoln
Model,1 Series M,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,...,Z8,Z8,ZDX,ZDX,ZDX,ZDX,ZDX,ZDX,ZDX,Zephyr
Year,2011,2011,2011,2011,2011,2012,2012,2012,2012,2013,...,2002,2003,2011,2011,2011,2012,2012,2012,2013,2006
Engine HP,335.0,300.0,300.0,230.0,230.0,230.0,300.0,300.0,230.0,230.0,...,394.0,394.0,300.0,300.0,300.0,300.0,300.0,300.0,300.0,221.0
Engine Cylinders,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,8.0,8.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
Transmission Type,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,...,MANUAL,MANUAL,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC
Vehicle Style,Coupe,Convertible,Coupe,Coupe,Convertible,Coupe,Convertible,Coupe,Convertible,Convertible,...,Convertible,Convertible,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,Sedan
highway MPG,26,28,28,28,28,28,26,28,28,27,...,19,19,23,23,23,23,23,23,23,26
city mpg,19,19,20,18,18,18,17,20,18,18,...,12,12,16,16,16,16,16,16,16,17

In [8]:
df_short.columns = df_short.columns.str.replace(' ', '_').str.lower()
df_short.T

,0,1,2,3,4,5,6,7,8,9,...,11904,11905,11906,11907,11908,11909,11910,11911,11912,11913
make,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,BMW,...,BMW,BMW,Acura,Acura,Acura,Acura,Acura,Acura,Acura,Lincoln
model,1 Series M,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,1 Series,...,Z8,Z8,ZDX,ZDX,ZDX,ZDX,ZDX,ZDX,ZDX,Zephyr
year,2011,2011,2011,2011,2011,2012,2012,2012,2012,2013,...,2002,2003,2011,2011,2011,2012,2012,2012,2013,2006
engine_hp,335.0,300.0,300.0,230.0,230.0,230.0,300.0,300.0,230.0,230.0,...,394.0,394.0,300.0,300.0,300.0,300.0,300.0,300.0,300.0,221.0
engine_cylinders,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,...,8.0,8.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0
transmission_type,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL,...,MANUAL,MANUAL,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC,AUTOMATIC
vehicle_style,Coupe,Convertible,Coupe,Coupe,Convertible,Coupe,Convertible,Coupe,Convertible,Convertible,...,Convertible,Convertible,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,4dr Hatchback,Sedan
highway_mpg,26,28,28,28,28,28,26,28,28,27,...,19,19,23,23,23,23,23,23,23,26
city_mpg,19,19,20,18,18,18,17,20,18,18,...,12,12,16,16,16,16,16,16,16,17

In [10]:
df_short.isna().sum()

make                  0
model                 0
year                  0
engine_hp            69
engine_cylinders     30
transmission_type     0
vehicle_style         0
highway_mpg           0
city_mpg              0
dtype: int64

In [12]:
df_short = df_short.fillna(0)
df_short.isna().sum()

make                 0
model                0
year                 0
engine_hp            0
engine_cylinders     0
transmission_type    0
vehicle_style        0
highway_mpg          0
city_mpg             0
dtype: int64

In [13]:
df_short['price'] = df['MSRP']
df_short.head().T

                            0            1         2         3            4
make                      BMW          BMW       BMW       BMW          BMW
model              1 Series M     1 Series  1 Series  1 Series     1 Series
year                     2011         2011      2011      2011         2011
engine_hp               335.0        300.0     300.0     230.0        230.0
engine_cylinders          6.0          6.0       6.0       6.0          6.0
transmission_type      MANUAL       MANUAL    MANUAL    MANUAL       MANUAL
vehicle_style           Coupe  Convertible     Coupe     Coupe  Convertible
highway_mpg                26           28        28        28           28
city_mpg                   19           19        20        18           18
price                   46135        40650     36350     29450        34500

In [19]:
df_short.transmission_type.value_counts()

transmission_type
AUTOMATIC           8266
MANUAL              2935
AUTOMATED_MANUAL     626
DIRECT_DRIVE          68
UNKNOWN               19
Name: count, dtype: int64

In [23]:
df_short.dtypes

corr_matrix = df_short[['year', 'engine_hp', 'engine_cylinders', 'highway_mpg', 'city_mpg', 'price']].corr()
corr_matrix

,year,engine_hp,engine_cylinders,highway_mpg,city_mpg,price
year,1.000000,0.338714,-0.040708,0.258240,0.198171,0.227590
engine_hp,0.338714,1.000000,0.774851,-0.415707,-0.424918,0.650095
engine_cylinders,-0.040708,0.774851,1.000000,-0.614541,-0.587306,0.526274
highway_mpg,0.258240,-0.415707,-0.614541,1.000000,0.886829,-0.160043
city_mpg,0.198171,-0.424918,-0.587306,0.886829,1.000000,-0.157676
price,0.227590,0.650095,0.526274,-0.160043,-0.157676,1.000000

In [32]:
mean_price = df_short.price.mean().__round__(0)
mean_price 

df_short.price = ((df_short.price - mean_price) > 0).astype(int)
df_short.head()

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,highway_mpg,city_mpg,price
0,BMW,1 Series M,2011,335.0,6.0,MANUAL,Coupe,26,19,1
1,BMW,1 Series,2011,300.0,6.0,MANUAL,Convertible,28,19,1
2,BMW,1 Series,2011,300.0,6.0,MANUAL,Coupe,28,20,0
3,BMW,1 Series,2011,230.0,6.0,MANUAL,Coupe,28,18,0
4,BMW,1 Series,2011,230.0,6.0,MANUAL,Convertible,28,18,0

In [36]:
from sklearn.model_selection import train_test_split

df_full_train, df_test = train_test_split(df_short, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)
len(df_train), len(df_val), len(df_test)

(7148, 2383, 2383)

In [37]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = df_train.price.values
y_val = df_val.price.values
y_test = df_test.price.values

df_train.drop(columns=['price'], inplace=True)
df_val.drop(columns=['price'], inplace=True)
df_test.drop(columns=['price'], inplace=True)

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,highway_mpg,city_mpg
0,Mitsubishi,Endeavor,2011,225.0,6.0,AUTOMATIC,4dr SUV,19,15
1,Kia,Borrego,2009,276.0,6.0,AUTOMATIC,4dr SUV,21,17
2,Lamborghini,Gallardo,2012,570.0,10.0,MANUAL,Convertible,20,12
3,Chevrolet,Colorado,2016,200.0,4.0,AUTOMATIC,Crew Cab Pickup,27,20
4,Pontiac,Vibe,2009,158.0,4.0,AUTOMATIC,4dr Hatchback,26,20

In [39]:
from sklearn.metrics import mutual_info_score

print('make')
print(mutual_info_score(y_train, df_train.make))

print('model')
print(mutual_info_score(y_train, df_train.model))

print('transmission_type')
print(mutual_info_score(y_train, df_train.transmission_type))

print('vehicle_style')
print(mutual_info_score(y_train, df_train.vehicle_style))

#'make', 'model', 'transmission_type', 'vehicle_style'

make
0.23976875439118345
model
0.46234389209653004
transmission_type
0.020957541896301862
vehicle_style
0.0841430195677944